config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
namespace :admins do
  get 'top' => 'homes#top',as: 'top'
  get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
  }

  scope module: :customers do
    root 'items#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  scope :only_active, -> { where(is_active: true) }

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  def full_name
    first_name + "　" + last_name
  end
  
  def full_name_kana
    first_name_kana + "　" + last_name_kana
  end
  
  def has_in_cart(item)
    cart_items.find_by(item_id: item.id)
  end
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_details
    has_many :items, through: :order_details

    validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
    validates :destination, presence: true
    validates :name, presence: true
    validates :shipping_cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :grand_total, presence: true, :numericality => { :greater_than_or_equal_to => 0 }

    scope :ordered_today, -> { where(created_at: Constants::BEGINNING_OF_TODAY...Constants::BEGINNING_OF_TOMORROW) }

    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }


    def shipping_information(resource)
        class_name = resource.class.name
        if class_name == "Customer"
            self.postal_code = resource.postal_code
            self.destination = resource.destination
            self.name = resource.full_name
        elsif class_name == "Address"
            self.postal_code = resource.postal_code
            self.destination = resource.destination
            self.name = resource.name
        end
    end
    
    def complete(user)
        Order.transaction do
            self.save!
            user.cart_items.each do |item|
                OrderDetail.create!(order_id: self.id, item_id: item.item.id, price: item.item.price, amount: item.amount)
                item.destroy!
            end
        end
    end
    
    def all_details_completed?
        order_details.completed.count == order_details.count
    end
    
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_customer, only: [:show, :edit, :update]
    
    def index
        @customers = Customer.all
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        @customer.update(customer_params) ? (redirect_to admins_customer_path(@customer)) : (render :edit)
    end
    
    private

    def customer_params
        params.require(:customer).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
    end

    def set_customer
        @customer = Customer.find(params[:id])
    end
    
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_order, only: [:show, :update]

    def index
        if params[:customer_id]
            @customer = Customer.find(params[:customer_id])
            @orders = @customer.orders.page(params[:page]).reverse_order
        elsif params[:created_at] == "today"
            @orders = Order.ordered_today.includes(:customer).page(params[:page]).reverse_order
        else
            @orders = Order.includes(:customer).page(params[:page]).reverse_order
        end
    end
    
    def show
        @customer = @order.customer
        @order_details = @order.order_details.includes(:item)
    end
    
    def update
        if @order.update(order_params) && @order.confirm_deposit?
            @order.order_details.update_all(making_status: 1)
        end
        redirect_to admins_order_path(@order)
    end
    
    private
    def set_order
        @order = Order.find(params[:id])
    end
    
    def order_params
        params.require(:order).permit(:status)
    end
    
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
    before_action :authenticate_customer!
    before_action :set_address, only: [:edit, :update, :destroy]

    def index
        @address  = Address.new
        @addresses = current_customer.addresses
    end
    
    def create
        # current_customer.addresses.newにするとエラー時にからレコードができてエラーになる。
        # ストロングパラメーターの中にユーザー情報入れて解決
        @address = Address.new(address_params)
        @addresses = current_customer.addresses
        @address.save ? (redirect_to addresses_path) : (render :index)
    end
    
    def edit
    end
    
    def update
        @address.update(address_params) ? (redirect_to addresses_path) : (render :edit)
    end
    
    def destroy
        @address.destroy
        redirect_to addresses_path
    end
    
    private
    def set_address
        @address = Address.find(params[:id])
    end
    
    def address_params
        params.require(:address).permit(:postal_code, :destination, :name).merge(customer_id: current_customer.id)
    end
    
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
    before_action :authenticate_customer!
    before_action :set_cart_item, only: [:create, :update, :destroy]

    def index
        @cart_items = current_customer.cart_items
    end
    
    def create
        if @cart_item
            @cart_item.update(cart_item_params)
            redirect_to cart_items_path
        else
            @cart_item = current_customer.cart_items.new(cart_item_params)
            @cart_item.item_id = @item.id
            @cart_item.save ? (redirect_to cart_items_path) : (render 'customers/items/show')
        end
    end
    
    def update
        @cart_item.update(cart_item_params)
        redirect_to cart_items_path
    end
    
    def destroy
        @cart_item.destroy
        redirect_to cart_items_path
    end
    
    def destroy_all
        current_customer.cart_items.destroy_all
        redirect_to cart_items_path
    end
    
    private

    def set_cart_item
        @item = Item.find(params[:item_id])
        @cart_item = current_customer.has_in_cart(@item)
    end
    
    def cart_item_params
        params.require(:cart_item).permit(:amount)
    end
    
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
    before_action :authenticate_customer!
    before_action :set_current_customer

    def show
    end
    
    def edit
    end
    
    def update
        @customer.update(customer_params) ? (redirect_to mypage_path) : (render :edit)
    end
    
    def unsubscribe
    end

    def withdraw
        @customer.update(is_active: false)
        reset_session
        redirect_to root_path
    end
    private

    def set_current_customer
        @customer = current_customer
    end
    
    def customer_params
    params.require(:customer).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number)
    end
    
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def top

  end

  def index
    @genres = Genre.where(is_active: true)
    if params[:genre_id]
      @genre = @genres.find(params[:genre_id])
      all_items = @genre.items
    else
      all_items = Item.where(is_active: true)
    end
    @items = all_items.page(params[:page]).per(12)
    @all_items_count = all_items.count
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(is_active: true)
    @cart_item = CartItem.new
  end
  
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
    before_action :authenticate_customer!
    before_action :ensure_cart_items, only: [:new, :confirm, :create, :error]

    def new
        @order = Order.new
    end
    
    def confirm
        @order = Order.new(order_params)
        if params[:select_address] == "0"
            @order.shipping_infomation(current_customer)
        elsif params[:select_address] == "1"
            @order.shipping_information(current_customer.addresses.find(params[:address_id]))
        elsif params[:select_address] == "2"
            # 不要
        else
            render :new
        end
    end
    
    def create
        @order = current_customer.orders.new(order_params)
        @order.complete(current_customer) ? (redirect_to thanks_path) : (render :new)
    end
    
    def thanks
    end
    
    def index
        @orders = current_customer.orders.includes(:order_details, :items).page(params[:page]).reverse_order
    end
    
    def show
        @order = Order.find(params[:id])
        @order_details = @order.order_details.includes(:item)
    end
    
    private

    def order_params
        params.require(:order).permit(:postal_code, :destination, :name, :payment_method, :grand_total).merge(shipping_cost: 800)
    end
    
    def ensure_cart_items
    @cart_items = current_customer.cart_items.includes(:item)
    redirect_to items_path unless @cart_items.first
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def after_sign_up_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/customers/orders/confirm.html.erb
<h2 class="section-ttl">注文情報確認</h2>
<div class="flex">
    <table class="confirm_cart_items mr2 mb3 has_border">
        <thead>
            <tr>
                <th colspan="2">商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
            </tr>
        </thead>
        <tbody>
            <% @cart_items.each do |cart_item| %>
                <% item = cart_item.item %>
                <tr>
                    <td>
                        <%= attachment_image_tag item, :image, format: "jpeg", fallback: "no-image.png", class: "cart_item_image", size: "100x100" %>
                    </td>
                    <td><%= item.name %></td>
                    <td><%= item.with_tax_price %>円</td>
                    <td><%= cart_item.amount %></td>
                    <td><%= cart_item.subtotal %>円</td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <table class="confirm_prices has_border">
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>送料</td>
                <td>800</td>
            </tr>
            <tr>
                <td>商品合計</td>
                <td><%= @cart_items.sum(&:subtotal) %></td>
            </tr>
            <tr>
                <td>総計</td>
                <td class="bold"><%= 800 + @cart_items.sum(&:subtotal) %></td>
            </tr>
        </tbody>
    </table>
</div>
<%= form_for(@order, url: orders_path) do |f| %>
    <div class="field">
        <%= f.label :payment_method, "支払い方法" %>
        <p><%= @order.payment_method_i18n %></p>
        <%= f.hidden_field :payment_method, value: @order.payment_method %>
    </div>
    <div class="field">
        <label>お届け先</label>
        <p>〒<%= @order.postal_code %> <%= @order.destination %><br><%= @order.name %></p>
        <%= f.hidden_field :postal_code, value: @order.postal_code %>
        <%= f.hidden_field :destination, value: @order.destination %>
        <%= f.hidden_field :name, value: @order.name %>
        <%= f.hidden_field :grand_total, value: 800 + @cart_items.sum(&:subtotal) %>
    </div>
    <div class="actions text-center">
        <%= f.submit "注文を確定する", class: "btn btn-primary submit_to_create_order" %>
    </div>
<% end %>

app/views/customers/orders/index.html.erb
<h2 class="section-ttl">注文履歴一覧</h2>
<table class="orders has_border">
    <thead>
        <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
        </tr>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
            <tr>
                <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                <td>
                    〒<%= order.postal_code %><br>
                    <%= order.destination %><br>
                    <%= order.name %>
                </td>
                <td>
                    <% order.items.each do |item| %>
                        <p><%= item.name %></p>
                    <% end %>
                </td>
                <td><%= order.grand_total %></td>
                <td class="text-center"><%= order.status_i18n %></td>
                <td class="text-center">
                    <%= link_to "表示する", order_path(order), class: "btn btn-primary" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @orders %>

app/views/customers/orders/new.html.erb
<h2 class="section-ttl">注文情報入力</h2>
<%= form_for(@order, url: orders_confirm_path) do |f| %>
    <div class="field mb2">
        <h3>支払い方法</h3>
    <%= f.radio_button :payment_method, "credit_card", :checked => true %>
    <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %> <!-- クレジットカード -->
    <%= f.radio_button :payment_method, "transfer" %>
    <%= f.label :payment_method, Order.payment_methods_i18n[:transfer] %> <!-- 銀行振込 -->
    </div>
    <h3>お届け先</h3>
    <div class="field mb2 select_address_0">
        <label class="fz16"><%= radio_button_tag :select_address, 0, :checked => true %>ご自身の住所</label>
        <p>〒<%= current_customer.postal_code %> <%= current_customer.address %></p>
        <p><%= current_customer.full_name %></p>
    </div>
    <div class="field mb2 select_address_1">
        <label class="fz16"><%= radio_button_tag "select_address", 1 %>登録済住所から選択</label>
        <%= select_tag "address_id", options_from_collection_for_select(current_customer.addresses, :id, :total_address), prompt: "住所を選択してください", disabled: true %>
    </div>
    <div class="field mb2 select_address_2">
        <label class="fz16"><%= radio_button_tag "select_address", 2 %>新しいお届け先</label>
        <div class="field">
            <%= f.label :postal_code, "郵便番号(ハイフンなし7桁)" %>
            <%= f.text_field :postal_code, autocomplete: "postal_code", placeholder: "郵便番号", disabled: true, class: "jpostal_code" %>
        </div>
        <div class="field">
            <%= f.label :destination, "住所(郵便番号から自動入力)" %>
            <%= f.text_field :destination, autocomplete: "destination", placeholder: "住所", disabled: true, class: "jpostal_address" %>
        </div>
        <div class="field">
            <%= f.label :name, "宛名" %>
            <%= f.text_field :name, autocomplete: "name", placeholder: "宛名", disabled: true %>
        </div>
    </div>
    <%= f.submit "注文確認画面に進む", class: "btn btn-primary submit_to_confirm_order" %>
<% end %>

app/views/customers/orders/show.html.erb
<h2 class="section-ttl">注文履歴詳細</h2>
<table class="order_info mb3 has_border">
    <caption class="fz16 text-left">注文情報</caption>
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
            <td>配送先</td>
            <td>
                〒<%= @order.postal_code %><br>
                <%= @order.destination %><br>
                <%= @order.name %>
            </td>
        </tr>
        <tr>
            <td>支払い方法</td>
            <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
            <td>ステータス</td>
            <td><%= @order.status_i18n %></td>
        </tr>
    </tbody>
</table>
<div class="flex">
    <table class="order_details mr2 has_border">
        <caption class="fz16 text-left">注文内容</caption>
        <thead>
            <tr>
                <th colspan="2">商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
            </tr>
        </thead>
        <tbody>
            <% @order.order_details.includes(:item).each do |order_detail| %>
                <% item = order_detail.item %>
                <tr>
                    <td>
                        <%= attachment_image_tag item, :image, format: "jpeg", fallback: "no-image.png", class: "cart_item_image", size:"100x100" %>
                    </td>
                    <td><%= link_to item.name, item_path(item) %></td>
                    <td class="text-right"><%= order_detail.price %>円</td>
                    <td class="text-center"><%= order_detail.amount %></td>
                    <td class="text-right"><%= order_detail.subtotal %>円</td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <table class="confirm_prices has_border">
        <caption class="fz16 text-left">請求情報</caption>
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>送料</td>
                <td><%= @order.shipping_cost %>円</td>
            </tr>
            <tr>
                <td>商品合計</td>
                <td><%= @order.order_details.sum(&:subtotal) %>円</td>
            </tr>
            <tr>
                <td>総計</td>
                <td class="bold"><%= @order.grand_total %>円</td>
            </tr>
        </tbody>
    </table>
</div>

app/views/customers/orders/thanks.html.erb
サンキューな！！！
面倒いので略
<%= link_to '買い物を続ける', items_path %>