config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
namespace :admins do
  get 'top' => 'homes#top',as: 'top'
  get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
  }

  scope module: :customers do
    root 'items#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_all_genre, only: [:index, :create]
    before_action :set_genre, only: [:edit, :update]

    def index
        @genre = Genre.new
    end
    
    def create
        @genre = Genre.new(genre_params)
        @genre.save ? (redirect_to admins_genres_path) : (render :index)
    end
    
    def edit
    end
    
    def update
        if @genre.update(genre_params)
            if @genre.is_active == false
                @genre.items.update_all(is_active: false)
            end
            redirect_to admins_genres_path
        else
            render :edit
        end
    end
    
    private

    def genre_params
        params.require(:genre).permit(:name, :is_active)
    end
    
    def set_all_genre
        @genres = Genre.all
    end
    
    def set_genre
        @genre = Genre.find(params[:id])
    end
    
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<h2>ジャンル編集</h2>
<%= form_for(＠genre, url: admins_genre_path) do |f| %>
	<%= render 'layouts/error_messages', resource: @genre %>
	<%= f.label :name, "ジャンル名:" %>
	<%= f.text_field :name %>
	<%= f.radio_button :is_active, true %>
	<%= f.label :is_active, "有効", class: "text-active" %>
	<%= f.radio_button :is_active, false %>
	<%= f.label :is_active, "無効", class: "text-invalid" %>
	<%= f.submit "編集する", class: "btn btn-primary ml2" %>
<% end %>

app/views/admins/genres/index.html.erb
<h2 class="section-ttl">ジャンル管理</h2>
<div class="mb3">
    <h3>ジャンル新規登録</h3>
    <%= form_for(@genre, url: admins_genres_path) do |f| %>
        <%= render 'layouts/error_messages', resource: @genre %>
        <%= f.label :name, "ジャンル名:" %>
        <%= f.text_field :name %>
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "有効", class: "text-active" %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "無効", class: "text-invalid" %>
        <%= f.submit "登録する", class: "btn btn-primary ml2" %>
    <% end %>
</div>
<div class="mb3">
    <h3>ジャンル一覧</h3>
    <table class="genre_info has_border">
        <thead>
            <tr>
                <th>ジャンル名</th>
                <th>状態</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @genres.each do |genre| %>
                <tr>
                    <td><%= link_to genre.name, admins_items_path(genre_id: genre.id), class: "underline" %></td>
                    <td>
                        <% if genre.is_active? %>
                            <span class="text-active">有効</span>
                        <% else %>
                            <span class="text-invalid">無効</span>
                        <% end %>
                    </td>
                    <td class="text-center"><%= link_to "編集", edit_admins_genre_path(genre), class: "btn btn-success" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>