config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
namespace :admins do
  get 'top' => 'homes#top',as: 'top'
  get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
  }

  scope module: :customers do
    root 'items#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  attachment :image

  def with_tax_price
    (price * 1.08).ceil
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_item, only: [:edit, :show, :update]

    def index
        if params[:genre_id]
            @genre = Genre.find(params[:genre_id])
            @items = @genre.items.page(params[:page])
        else
            @items = Item.all.page(params[:page])
        end
        @items_count = @items.count
    end
    
    def create
        @item.new(item_params)
        @item.save ? (redirect_to admins_item_path(@item)) : (render :new)
    end
    
    def new
        @item = Item.new
    end
    
    def edit
    end
    
    def show
    end
    
    def update
        @item.update(item_params) ? (redirect_to admins_item_path(@item)) : (render :edit)
    end
    
    private
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_active)
    end
    
    def set_item
        @item = Item.find(params[:id])
    end
    
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def top

  end

  def index
    @genres = Genre.where(is_active: true)
    if params[:genre_id]
      @genre = @genres.find(params[:genre_id])
      all_items = @genre.items
    else
      all_items = Item.where(is_active: true)
    end
    @items = all_items.page(params[:page]).per(12)
    @all_items_count = all_items.count
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(is_active: true)
    @cart_item = CartItem.new
  end
  
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/views/admins/items/edit.html.erb
<h2 class="section-ttl"><%= @item.name %>の編集</h2>
<%= form_for(@item, url: admins_item_path(@item)) do |f| %>
	<%= render 'layouts/error_messages', resource: @item %>
	<div class="flex">
		<div>
			<%= f.label :image, "画像" %>
			<div class="image_field">
				<%= attachment_image_tag @item, :image, format: "jpeg", id: "img_prev", fallback: "no-image.png", size: '100x100', class: "admin_item_image" %>
				<span class="btn btn-file btn-info"><%= f.attachment_field :image %>画像選択</span>
				<p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「画像準備中」になります。</p>
			</div>
		</div>
		<table class="admin_item_info item_form">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= f.label :name, "商品名" %></td>
					<td><%= f.text_field :name %></td>
				</tr>
				<tr>
					<td><%= f.label :introduction, "商品説明" %></td>
					<td><%= f.text_area :introduction, rows: 3 %></td>
				</tr>
				<tr>
					<td><%= f.label :genre_id, "ジャンル" %></td>
					<td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
				</tr>
				<tr>
					<td><%= f.label :price, "税抜価格" %></td>
					<td><%= f.number_field :price %> 円</td>
				</tr>
				<tr>
					<td><%= f.label :sales_status, "販売ステータス" %></td>
					<td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "販売中", class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "販売停止中", class: "text-invalid" %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="flex align-center pl5">
            <%= f.submit "更新する", class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/admins/items/index.html.erb
<div class="inner">
    <% if params[:genre_id] %>
        <h2 class="section-ttl"><%= @genre.name %>の商品一覧 (全<%= @items_count %>件)</h2>
    <% else %>
        <h2 class="section-ttl">商品一覧 (全<%= @items_count %>件)</h2>
    <% end %>
    <h4 class="text-right">
        <%= link_to "新規商品登録", new_admins_item_path, class: "new_admin_item" %>
    </h4>
    <% if @items.first %> <!-- @item.existsと同義、SQL1個分削減(?) -->
        <table class="admin_items has_border">
            <thead>
                <tr>
                    <th>商品ID</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                    <th>ジャンル</th>
                    <th>販売ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @items.each do |item| %>
                    <tr>
                        <td class="text-center"><%= item.id %></td>
                        <td><%= link_to item.name, admins_item_path(item), class: "underline" %></td>
                        <td class="text-center"><%= item.price %>円</td>
                        <td><%= link_to item.genre.name, admins_items_path(genre_id: item.genre_id) %></td>
                        <td>
                            <% if item.is_active? %>
                                <span class="text-active">販売中</span>
                            <% else %>
                                <span class="text-invalid">販売停止中</span>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate @items %>
    <% else %>
        <h3>対応する商品はありませんでした。</h3>
    <% end %>
</div>

app/views/admins/items/new.html.erb
<h2 class="section-ttl">商品新規登録</h2>
<%= form_for(@item, url: admins_items_path) do |f| %>
	<%= render 'layouts/error_messages', resource: @item %>
	<div class="flex">
		<div>
			<%= f.label :image, "画像" %>
			<div class="image_field">
				<%= attachment_image_tag @item, :image, format: "jpeg", id: "img_prev", fallback: "no-image.png", class: "admin_item_image" %>
				<span class="btn btn-file btn-info"><%= f.attachment_field :image %>画像選択</span>
				<p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「画像準備中」になります。</p>
			</div>
		</div>
		<table class="admin_item_info item_form">
			<thead>
				<tr>
					<th></th>	
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= f.label :name, "商品名" %></td>
					<td><%= f.text_field :name %></td>
				</tr>
				<tr>
					<td><%= f.label :introduction, "商品説明" %></td>
					<td><%= f.text_area :introduction, rows: 3 %></td>
				</tr>
				<tr>
					<td><%= f.label :genre_id, "ジャンル" %></td>
					<td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
				</tr>
				<tr>
					<td><%= f.label :price, "税抜価格" %></td>
					<td><%= f.number_field :price %> 円</td>
				</tr>
				<tr>
					<td><%= f.label :sales_status, "販売ステータス" %></td>
					<td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "販売中", class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "販売停止中", class: "text-invalid" %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="flex align-center pl5">
			<%= f.submit submit, class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/admins/items/show.html.erb
<h2 class="section-ttl">商品詳細</h2>
<div class="flex">
    <div>
        <div class="image_field">
            <%= attachment_image_tag @item, :image, format: "jpeg", id: "img_prev", fallback: "no-image.png",size: '100x100', class: "admin_item_image" %>
        </div>
    </div>
    <table class="admin_item_info">
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>商品名</td>
                <td><%= @item.name %></td>
            </tr>
            <tr>
                <td>商品説明</td>
                <td><%= @item.introduction %></td>
            </tr>
            <tr>
                <td>ジャンル</td>
                <td><%= link_to @item.genre.name, admins_items_path(genre_id: @item.genre_id) %></td>
            </tr>
            <tr>
                <td>税抜価格</td>
                <td><%= @item.price %>円</td>
            </tr>
            <tr>
                <td>販売ステータス</td>
                <td>
                    <% if @item.is_active? %>
                        <span class="text-active">販売中</span>
                    <% else %>
                        <span class="text-invalid">販売停止中</span>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="flex align-center pl5">
        <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success" %>
    </div>
</div>