config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
namespace :admins do
  get 'top' => 'homes#top',as: 'top'
  get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end


  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
  }

  scope module: :customers do
    root 'items#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
      belongs_to :customer

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :destination, presence: true
  validates :name, presence: true

  def total_address
    '〒' + postal_code + ' ' + destination + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    validates :item_id, uniqueness: { scope: :customer_id }
    validates :amount, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  scope :only_active, -> { where(is_active: true) }

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  def full_name
    first_name + "　" + last_name
  end
  
  def full_name_kana
    first_name_kana + "　" + last_name_kana
  end
  
  def has_in_cart(item)
    cart_items.find_by(item_id: item.id)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  attachment :image

  def with_tax_price
    (price * 1.08).ceil
  end
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_details
    has_many :items, through: :order_details

    validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
    validates :destination, presence: true
    validates :name, presence: true
    validates :shipping_cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :grand_total, presence: true, :numericality => { :greater_than_or_equal_to => 0 }

    scope :ordered_today, -> { where(created_at: Constants::BEGINNING_OF_TODAY...Constants::BEGINNING_OF_TOMORROW) }

    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }


    def shipping_information(resource)
        class_name = resource.class.name
        if class_name == "Customer"
            self.postal_code = resource.postal_code
            self.destination = resource.destination
            self.name = resource.full_name
        elsif class_name == "Address"
            self.postal_code = resource.postal_code
            self.destination = resource.destination
            self.name = resource.name
        end
    end
    
    def complete(user)
        Order.transaction do
            self.save!
            user.cart_items.each do |item|
                OrderDetail.create!(order_id: self.id, item_id: item.item.id, price: item.item.price, amount: item.amount)
                item.destroy!
            end
        end
    end
    
    def all_details_completed?
        order_details.completed.count == order_details.count
    end
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    validates :item_id, uniqueness: { scope: :order_id }
    validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :amount, presence: true, :numericality => { :greater_than_or_equal_to => 1 }

    enum making_status: { cannot_start: 0, waiting_start: 1, in_production: 2, completed: 3 }

    def subtotal
        price * amount
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。以下ご確認お願いいたします。</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="container">
      <% if admin_signed_in? %>
        <div class='nav navbar-nav navbar-left'>
          <%= link_to 'NaganoCake', admins_top_path %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '商品一覧', admins_items_path %></li>
          <li><%= link_to '会員一覧', admins_customers_path %></li>
          <li><%= link_to '注文履歴一覧', admins_orders_path %></li>
          <li><%= link_to 'ジャンル一覧', admins_genres_path %></li>
          <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
        </ul>
      <% elsif customer_signed_in? %>
        <div class='nav navbar-nav navbar-left'>
          <%= link_to 'NaganoCake', root_path %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'マイページ', mypage_path %></li>
          <li><%= link_to '商品一覧', items_path %></li>
          <li><%= link_to 'カート', cart_items_path %></li>
          <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <div class='nav navbar-nav navbar-left'>
          <%= link_to 'NaganoCake', root_path %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '商品一覧', items_path %></li>
          <li><%= link_to '新規登録', new_customer_registration_path %></li>
          <li><%= link_to 'ログイン', new_customer_session_path %></li>
        </ul>
      <% end %>
    </div>
  </header>
    <%= yield %>
  </body>
</html>